{
 "title": "Demo - Git-Sync Demo 1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU - Melbourne South East",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aws_ec2_cpuutilization_average{region=\"ap-southeast-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{scrape_job=\"cg-aws-scrape-cloudwatch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "aws_ec2_cpuutilization_average{region=\"us-east-1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}